/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import GooglePlayImage from 'src/assets/images/Hompage_Google_Play_1.png';
import GetItOnImage from 'src/assets/images/Hompage_Get_it_on_1.png';
import VectorImage from 'src/assets/images/Hompage_Vector_31.png';
import Vector1Image from 'src/assets/images/Hompage_Vector_30.png';
import Vector2Image from 'src/assets/images/Hompage_Vector_29.png';
import Vector3Image from 'src/assets/images/Hompage_Vector_28.png';
import AppStoreImage from 'src/assets/images/Hompage_App_Store_1.png';
import DownloadOnTheImage from 'src/assets/images/Hompage_Download_on_the_1.png';
import AppleLogoImage from 'src/assets/images/Hompage_Apple_logo_1.png';
import DividerImage from 'src/assets/images/Hompage_Divider_1.png';
import Image39Image from 'src/assets/images/Hompage_image_39.png';
import HubspotLogoImage from 'src/assets/images/Hompage_Hubspot_Logo.svg';
import Image3Image from 'src/assets/images/Hompage_image_3.png';
import MicrosoftLogoImage from 'src/assets/images/Hompage_Microsoft_Logo.svg';
import WalmartLogoImage from 'src/assets/images/Hompage_Walmart_Logo.svg';
import Image4Image from 'src/assets/images/Hompage_image_4.png';
import Divider1Image from 'src/assets/images/Hompage_Divider.png';
import Ellipse12Image from 'src/assets/images/Hompage_Ellipse_12.png';
import Vector4Image from 'src/assets/images/Hompage_Vector_27.png';
import Vector5Image from 'src/assets/images/Hompage_Vector_26.png';
import Vector6Image from 'src/assets/images/Hompage_Vector_25.png';
import Ellipse13Image from 'src/assets/images/Hompage_Ellipse_13.png';
import Vector7Image from 'src/assets/images/Hompage_Vector_24.png';
import Ellipse14Image from 'src/assets/images/Hompage_Ellipse_14.png';
import Path14Image from 'src/assets/images/Hompage_path14.png';
import Path16Image from 'src/assets/images/Hompage_path16.png';
import Ellipse15Image from 'src/assets/images/Hompage_Ellipse_15.png';
import Path2520Image from 'src/assets/images/Hompage_Path_2520.png';
import Vector51Image from 'src/assets/images/Hompage_Vector_5_1.png';
import Vector8Image from 'src/assets/images/Hompage_Vector_23.png';
import Vector9Image from 'src/assets/images/Hompage_Vector_22.png';
import Vector10Image from 'src/assets/images/Hompage_Vector_21.png';
import Vector11Image from 'src/assets/images/Hompage_Vector_20.png';
import Vector12Image from 'src/assets/images/Hompage_Vector_19.png';
import Vector13Image from 'src/assets/images/Hompage_Vector_18.png';
import Vector14Image from 'src/assets/images/Hompage_Vector_17.png';
import Vector15Image from 'src/assets/images/Hompage_Vector_16.png';
import Vector16Image from 'src/assets/images/Hompage_Vector_15.png';
import Vector17Image from 'src/assets/images/Hompage_Vector_14.png';
import PathImage from 'src/assets/images/Hompage_Path_1.png';
import Path1Image from 'src/assets/images/Hompage_Path.png';
import Vector18Image from 'src/assets/images/Hompage_Vector_13.png';
import Vector19Image from 'src/assets/images/Hompage_Vector_12.png';
import Vector20Image from 'src/assets/images/Hompage_Vector_11.png';
import Vector21Image from 'src/assets/images/Hompage_Vector_10.png';
import Vector22Image from 'src/assets/images/Hompage_Vector_9.png';
import Vector23Image from 'src/assets/images/Hompage_Vector_8.png';
import Vector24Image from 'src/assets/images/Hompage_Vector_7.png';
import Vector25Image from 'src/assets/images/Hompage_Vector_6.png';
import Vector26Image from 'src/assets/images/Hompage_Vector_5.png';
import Vector27Image from 'src/assets/images/Hompage_Vector_4.png';
import GooglePlay1Image from 'src/assets/images/Hompage_Google_Play.png';
import GetItOn1Image from 'src/assets/images/Hompage_Get_it_on.png';
import Vector28Image from 'src/assets/images/Hompage_Vector_3.png';
import Vector29Image from 'src/assets/images/Hompage_Vector_2.png';
import Vector30Image from 'src/assets/images/Hompage_Vector_1.png';
import Vector31Image from 'src/assets/images/Hompage_Vector.png';
import AppStore1Image from 'src/assets/images/Hompage_App_Store.png';
import DownloadOnThe1Image from 'src/assets/images/Hompage_Download_on_the.png';
import AppleLogo1Image from 'src/assets/images/Hompage_Apple_logo.png';
import MaskGroupImage from 'src/assets/images/Hompage_Mask_Group_6.png';
import Image52Image from 'src/assets/images/Hompage_image_52.png';
import Arrow6Image from 'src/assets/images/Hompage_Arrow_6_1.png';
import Image51Image from 'src/assets/images/Hompage_image_51.png';
import Arrow61Image from 'src/assets/images/Hompage_Arrow_6.png';
import Image54Image from 'src/assets/images/Hompage_image_54.png';
import Rectangle3102Image from 'src/assets/images/Hompage_Rectangle_3102.png';
import MaskGroup1Image from 'src/assets/images/Hompage_Mask_Group_5.png';
import MaskGroup2Image from 'src/assets/images/Hompage_Mask_Group_4.png';
import MaskGroup3Image from 'src/assets/images/Hompage_Mask_Group_3.png';
import MaskGroup4Image from 'src/assets/images/Hompage_Mask_Group_2.png';
import MaskGroup5Image from 'src/assets/images/Hompage_Mask_Group_1.png';
import MaskGroup6Image from 'src/assets/images/Hompage_Mask_Group.png';
import Image53Image from 'src/assets/images/Hompage_image_53.png';
import Ellipse775Image from 'src/assets/images/Hompage_Ellipse_775_1.png';
import Arrow1Image from 'src/assets/images/Hompage_Arrow_1_1.png';
import Ellipse7751Image from 'src/assets/images/Hompage_Ellipse_775.png';
import Arrow11Image from 'src/assets/images/Hompage_Arrow_1.png';
import { styled } from '@mui/material/styles';
import DownloadBadgeGooglePlayBadge from 'src/components/DownloadBadgeGooglePlayBadge/DownloadBadgeGooglePlayBadge';
import DownloadBadgeAppStoreBadge from 'src/components/DownloadBadgeAppStoreBadge/DownloadBadgeAppStoreBadge';
import Group1000001796 from 'src/components/Group1000001796/Group1000001796';

 
const Hompage1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: "auto",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Community = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(83, 86, 89, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `153.20000648498535%`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `884px`,  
  top: `70px`,  
});
  
const Insights = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(83, 86, 89, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `153.20000648498535%`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `776px`,  
  top: `70px`,  
});
  
const Learn = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(83, 86, 89, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `153.20000648498535%`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `605px`,  
  top: `70px`,  
});
  
const Loan = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(83, 86, 89, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `153.20000648498535%`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `694px`,  
  top: `70px`,  
});
  
const AboutUs = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(83, 86, 89, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `153.20000648498535%`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `482px`,  
  top: `70px`,  
});
  
const SignIn = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `153.20000648498535%`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `214px`,  
  top: `737px`,  
});
  
const Group1000001865 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1200px`,  
  height: `219px`,  
  left: `120px`,  
  top: `5097px`,  
});
  
const Group1000001864 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1200px`,  
  height: `219px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group1000001704 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1200px`,  
  height: `219px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Rectangle127 = styled("div")({  
  background: `linear-gradient(100.34deg, rgba(237, 31, 142, 1) 0.0025923942859696967%, rgba(251, 242, 242, 1) 100.00186241002807%)`,  
  borderRadius: `15px`,  
  width: `1200px`,  
  height: `219px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const StartBuildingWealthTSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Eina02-`,  
  fontWeight: `400`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `uppercase`,  
});
  
const StartBuildingWealthTSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Eina02-`,  
  fontWeight: `700`,  
  fontSize: `36px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `none`,  
});
  
const StartBuildingWealthT = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: "unset",  
  fontWeight: `400`,  
  fontSize: `nullpx`,  
  letterSpacing: `NaNpx`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `none`,  
  width: `574px`,  
  position: `absolute`,  
  left: `103px`,  
  top: `67px`,  
});
  
const Group1000001705 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `360px`,  
  height: `58.67px`,  
  left: `735px`,  
  top: `81px`,  
});
  
const Rectangle103 = styled("div")({  
  backgroundColor: `rgba(3, 0, 39, 1)`,  
  borderRadius: `65px`,  
  width: `168px`,  
  height: `58.67px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group1000001660 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `123.87px`,  
  height: `28.84px`,  
  left: `22px`,  
  top: `15px`,  
});
  
const Group7133 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `84.78px`,  
  height: `28.84px`,  
  left: `39px`,  
  top: `0px`,  
});
  
const GooglePlay = styled("img")({  
  height: `18.05px`,  
  width: `84.78px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `11px`,  
});
  
const GetItOn = styled("img")({  
  height: `6.64px`,  
  width: `38.85px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const GooglePlayLogo = styled("div")({  
  boxShadow: `inset 0px -0.15000000596046448px 0px rgba(0, 0, 0, 0.12), inset 0px 0.15000000596046448px 0px rgba(255, 255, 255, 0.25)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `23.09px`,  
  height: `27.26px`,  
  left: `0px`,  
  top: `1px`,  
});
  
const Vector = styled("img")({  
  height: `26.57px`,  
  width: `12.93px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector1 = styled("img")({  
  height: `9.06px`,  
  width: `10.16px`,  
  position: `absolute`,  
  left: `13px`,  
  top: `9px`,  
});
  
const Vector2 = styled("img")({  
  height: `13.63px`,  
  width: `16.69px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `14px`,  
});
  
const Vector3 = styled("img")({  
  height: `13.63px`,  
  width: `16.69px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Rectangle104 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 240, 248, 1)`,  
  borderRadius: `65px`,  
  width: `168px`,  
  height: `58.67px`,  
  position: `absolute`,  
  left: `192px`,  
  top: `0px`,  
}));
  
const Group7135 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `108.79px`,  
  height: `26.58px`,  
  left: `222px`,  
  top: `16px`,  
});
  
const Group7134 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `75.08px`,  
  height: `26.58px`,  
  left: `34px`,  
  top: `0px`,  
});
  
const AppStore = styled("img")({  
  height: `16.66px`,  
  width: `75.08px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `10px`,  
});
  
const DownloadOnThe = styled("img")({  
  height: `6.75px`,  
  width: `69.15px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `0px`,  
});
  
const AppleLogo = styled("img")({  
  height: `23.08px`,  
  width: `17.72px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `2px`,  
});
  
const LogoClouds1 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1440px`,  
  height: `142px`,  
  left: `0px`,  
  top: `922px`,  
}));
  
const Divider = styled("img")({  
  height: `2px`,  
  width: `911px`,  
  position: `absolute`,  
  left: `364px`,  
  top: `15px`,  
});
  
const OurPartners = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(107, 107, 107, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `6.08px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `165px`,  
  top: `6px`,  
});
  
const Logos = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `16px 0px`,  
  boxSizing: `border-box`,  
  left: `220px`,  
  top: `4px`,  
  overflow: `hidden`,  
});
  
const Image39 = styled("img")({  
  height: `37px`,  
  width: `37px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const HubspotLogo = styled("img")({  
  height: `auto`,  
  width: `84px`,  
  margin: `0px 0px 0px 64px`,  
});
  
const Image3 = styled("img")({  
  height: `103px`,  
  width: `195.66px`,  
  objectFit: `cover`,  
  margin: `0px 0px 0px 64px`,  
});
  
const MicrosoftLogo = styled("img")({  
  height: `auto`,  
  width: `122px`,  
  margin: `0px 0px 0px 64px`,  
});
  
const WalmartLogo = styled("img")({  
  height: `auto`,  
  width: `111px`,  
  margin: `0px 0px 0px 64px`,  
});
  
const Image4 = styled("img")({  
  height: `73.09px`,  
  width: `129.8px`,  
  objectFit: `cover`,  
  margin: `0px 0px 0px 64px`,  
});
  
const Divider1 = styled("img")({  
  height: `2px`,  
  width: `1110px`,  
  position: `absolute`,  
  left: `165px`,  
  top: `125px`,  
});
  
const MacBookPro22 = styled("div")({  
  backgroundColor: `rgba(0, 0, 0, 1)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1440px`,  
  height: `634px`,  
  left: `0px`,  
  top: `5445px`,  
  overflow: `hidden`,  
});
  
const Group72 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `86px`,  
  height: `217px`,  
  left: `714px`,  
  top: `106px`,  
});
  
const Support = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `900`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const HelpCenter = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `46px`,  
});
  
const FaQs = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `84px`,  
});
  
const Community1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `122px`,  
});
  
const ContactUs = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `160px`,  
});
  
const Careers = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `198px`,  
});
  
const Group73 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `102px`,  
  height: `217px`,  
  left: `515px`,  
  top: `106px`,  
});
  
const WhoWeAre = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `900`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const AboutUs1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `46px`,  
});
  
const WhatWeDo = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `84px`,  
});
  
const WhoWeServe = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `122px`,  
});
  
const OurPeople = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `160px`,  
});
  
const OurServices = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `198px`,  
});
  
const Group43 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `127px`,  
  height: `141px`,  
  left: `883px`,  
  top: `106px`,  
});
  
const Legal = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `900`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const CookiesPolicy = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `46px`,  
});
  
const PrivacyPolicy = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `84px`,  
});
  
const TermsOfServices = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `122px`,  
});
  
const Group38 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `184px`,  
  height: `75px`,  
  left: `1162px`,  
  top: `106px`,  
});
  
const ConnectWithUs = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(232, 244, 217, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group30 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `40px`,  
  height: `40px`,  
  left: `0px`,  
  top: `35px`,  
});
  
const Ellipse12 = styled("img")({  
  height: `40px`,  
  width: `40px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const InstagramIcon = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `20px`,  
  height: `20px`,  
  left: `10px`,  
  top: `10px`,  
  overflow: `hidden`,  
});
  
const Vector4 = styled("img")({  
  height: `19.7px`,  
  width: `19.7px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector5 = styled("img")({  
  height: `19.7px`,  
  width: `19.7px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector6 = styled("img")({  
  height: `14.55px`,  
  width: `14.54px`,  
  position: `absolute`,  
  left: `3px`,  
  top: `3px`,  
});
  
const Group29 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `40px`,  
  height: `40px`,  
  left: `48px`,  
  top: `35px`,  
});
  
const Ellipse13 = styled("img")({  
  height: `40px`,  
  width: `40px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const TwitterLogo = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `17.97px`,  
  height: `14.62px`,  
  left: `11px`,  
  top: `13px`,  
  overflow: `hidden`,  
});
  
const Group = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `17.85px`,  
  height: `14.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector7 = styled("img")({  
  height: `14.5px`,  
  width: `17.85px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group28 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `40px`,  
  height: `40px`,  
  left: `96px`,  
  top: `35px`,  
});
  
const Ellipse14 = styled("img")({  
  height: `40px`,  
  width: `40px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const FacebookIcon = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `20px`,  
  height: `20px`,  
  left: `10px`,  
  top: `10px`,  
  overflow: `hidden`,  
});
  
const G10 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `8.55px`,  
  height: `16.09px`,  
  left: `6px`,  
  top: `20px`,  
});
  
const G12 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `8.55px`,  
  height: `16.09px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Path14 = styled("img")({  
  height: `19.88px`,  
  width: `20px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Path16 = styled("img")({  
  height: `16.09px`,  
  width: `8.55px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group27 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `40px`,  
  height: `40px`,  
  left: `144px`,  
  top: `35px`,  
});
  
const Ellipse15 = styled("img")({  
  height: `40px`,  
  width: `40px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const LinkedInIcon = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `16px`,  
  height: `16px`,  
  left: `12px`,  
  top: `12px`,  
  overflow: `hidden`,  
});
  
const Path2520 = styled("img")({  
  height: `15.87px`,  
  width: `16.03px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const ThisSiteUsesCookiesCSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
});
  
const ThisSiteUsesCookiesCSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(235, 37, 144, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
});
  
const ThisSiteUsesCookiesCSpan3 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
});
  
const ThisSiteUsesCookiesCSpan4 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(235, 37, 144, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
});
  
const ThisSiteUsesCookiesCSpan5 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
});
  
const ThisSiteUsesCookiesCSpan6 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(235, 37, 144, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
});
  
const ThisSiteUsesCookiesCSpan7 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
});
  
const ThisSiteUsesCookiesC = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `93px`,  
  top: `459px`,  
});
  
const Copyright2021Sheclud = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `94px`,  
  top: `561px`,  
});
  
const Vector51 = styled("img")({  
  height: `0px`,  
  width: `1276px`,  
  position: `absolute`,  
  left: `97px`,  
  top: `521px`,  
});
  
const Col4 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `136.34px`,  
  left: `1162px`,  
  top: `228px`,  
  overflow: `hidden`,  
});
  
const InstallApp = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(244, 245, 247, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Eina02-`,  
  fontWeight: `700`,  
  fontSize: `14.268291473388672px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `22.19512176513672px`,  
  textTransform: `none`,  
  height: `22.2px`,  
  width: `72.13px`,  
  margin: `0px`,  
}));
  
const Badges = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `19.024389266967773px 0px 0px 0px`,  
  overflow: `hidden`,  
});
  
const DownloadBadgeGoogleP = styled(DownloadBadgeGooglePlayBadge)(({ theme }) =>({  
  height: `38.05px`,  
  width: `128.41px`,  
  margin: `0px`,  
}));
  
const DownloadBadgeAppStor = styled(DownloadBadgeAppStoreBadge)(({ theme }) =>({  
  height: `38.05px`,  
  width: `128.41px`,  
  margin: `12.682926177978516px 0px 0px 0px`,  
}));
  
const Logo21 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `221px`,  
  height: `34.94px`,  
  left: `85px`,  
  top: `106px`,  
  overflow: `hidden`,  
});
  
const Layer2 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `221px`,  
  height: `34.94px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Layer1 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `221px`,  
  height: `34.94px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector8 = styled("img")({  
  height: `34.94px`,  
  width: `34.94px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector9 = styled("img")({  
  height: `20.43px`,  
  width: `15.4px`,  
  position: `absolute`,  
  left: `42px`,  
  top: `10px`,  
});
  
const Vector10 = styled("img")({  
  height: `27.61px`,  
  width: `17.24px`,  
  position: `absolute`,  
  left: `61px`,  
  top: `2px`,  
});
  
const Vector11 = styled("img")({  
  height: `20.43px`,  
  width: `19.54px`,  
  position: `absolute`,  
  left: `82px`,  
  top: `10px`,  
});
  
const Vector12 = styled("img")({  
  height: `20.39px`,  
  width: `17.65px`,  
  position: `absolute`,  
  left: `104px`,  
  top: `10px`,  
});
  
const Vector13 = styled("img")({  
  height: `27.61px`,  
  width: `3.69px`,  
  position: `absolute`,  
  left: `125px`,  
  top: `2px`,  
});
  
const Vector14 = styled("img")({  
  height: `19.95px`,  
  width: `17.23px`,  
  position: `absolute`,  
  left: `133px`,  
  top: `10px`,  
});
  
const Vector15 = styled("img")({  
  height: `28.1px`,  
  width: `20.44px`,  
  position: `absolute`,  
  left: `154px`,  
  top: `2px`,  
});
  
const Vector16 = styled("img")({  
  height: `20.43px`,  
  width: `19.54px`,  
  position: `absolute`,  
  left: `178px`,  
  top: `10px`,  
});
  
const Vector17 = styled("img")({  
  height: `28.1px`,  
  width: `20.44px`,  
  position: `absolute`,  
  left: `201px`,  
  top: `2px`,  
});
  
const Newsletter = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `289px`,  
  height: `139px`,  
  left: `85px`,  
  top: `187px`,  
  overflow: `hidden`,  
});
  
const SubscribeToOurNew = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `DM Sans`,  
  fontWeight: `400`,  
  fontSize: `22px`,  
  letterSpacing: `-0.30000001192092896px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Form = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `289px`,  
  height: `51px`,  
  left: `0px`,  
  top: `88px`,  
  overflow: `hidden`,  
});
  
const Rectangle = styled("div")({  
  opacity: `0.10000000149011612`,  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  width: `289px`,  
  height: `1px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `50px`,  
});
  
const EmailAddress = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `DM Sans`,  
  fontWeight: `400`,  
  fontSize: `15px`,  
  letterSpacing: `-0.20454545319080353px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  opacity: `0.5`,  
  position: `absolute`,  
  left: `0px`,  
  top: `10px`,  
});
  
const Submit = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `50px`,  
  height: `50px`,  
  left: `239px`,  
  top: `0px`,  
});
  
const Rectangle1 = styled("div")({  
  backgroundColor: `rgba(235, 37, 144, 1)`,  
  borderRadius: `8px 8px 0px 0px`,  
  width: `50px`,  
  height: `50px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const IcKeyboardArrowRight = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `20px`,  
  height: `20px`,  
  left: `15px`,  
  top: `15px`,  
});
  
const Path = styled("img")({  
  height: `10px`,  
  width: `6.18px`,  
  position: `absolute`,  
  left: `7px`,  
  top: `5px`,  
});
  
const Path1 = styled("img")({  
  height: `20px`,  
  width: `20px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Layer21 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `196.1px`,  
  height: `31px`,  
  left: `138px`,  
  top: `70px`,  
});
  
const Layer11 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `196.1px`,  
  height: `31px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector18 = styled("img")({  
  height: `31px`,  
  width: `31px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector19 = styled("img")({  
  height: `18.13px`,  
  width: `13.66px`,  
  position: `absolute`,  
  left: `37px`,  
  top: `9px`,  
});
  
const Vector20 = styled("img")({  
  height: `24.5px`,  
  width: `15.3px`,  
  position: `absolute`,  
  left: `54px`,  
  top: `2px`,  
});
  
const Vector21 = styled("img")({  
  height: `18.13px`,  
  width: `17.34px`,  
  position: `absolute`,  
  left: `73px`,  
  top: `9px`,  
});
  
const Vector22 = styled("img")({  
  height: `18.1px`,  
  width: `15.66px`,  
  position: `absolute`,  
  left: `93px`,  
  top: `9px`,  
});
  
const Vector23 = styled("img")({  
  height: `24.5px`,  
  width: `3.28px`,  
  position: `absolute`,  
  left: `110px`,  
  top: `2px`,  
});
  
const Vector24 = styled("img")({  
  height: `17.7px`,  
  width: `15.29px`,  
  position: `absolute`,  
  left: `118px`,  
  top: `9px`,  
});
  
const Vector25 = styled("img")({  
  height: `24.93px`,  
  width: `18.14px`,  
  position: `absolute`,  
  left: `137px`,  
  top: `2px`,  
});
  
const Vector26 = styled("img")({  
  height: `18.13px`,  
  width: `17.33px`,  
  position: `absolute`,  
  left: `158px`,  
  top: `9px`,  
});
  
const Vector27 = styled("img")({  
  height: `24.93px`,  
  width: `18.14px`,  
  position: `absolute`,  
  left: `178px`,  
  top: `2px`,  
});
  
const Frame1000002123 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  left: `133px`,  
  top: `258px`,  
});
  
const Group1000001813 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `43px`,  
  width: `446px`,  
  margin: `0px`,  
});
  
const Rectangle3110 = styled("div")(({ theme }) =>({  
  opacity: `0.10000000149011612`,  
  backgroundColor: `rgba(245, 152, 216, 1)`,  
  borderRadius: `55px`,  
  width: `446px`,  
  height: `43px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const BrandAnnouncementWeHSpan1 = styled("span")(({ theme }) =>({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(235, 37, 144, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
}));
  
const BrandAnnouncementWeHSpan2 = styled("span")(({ theme }) =>({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(235, 37, 144, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `underline`,  
  textTransform: `none`,  
}));
  
const BrandAnnouncementWeH = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(235, 37, 144, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `18px`,  
  top: `12px`,  
}));
  
const Frame1000002122 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `31px 0px 0px 0px`,  
});
  
const PoweringFinanceForFeSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `70px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `108.00000429153442%`,  
  textTransform: `capitalize`,  
});
  
const PoweringFinanceForFeSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(235, 37, 144, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Playfair Display`,  
  fontWeight: `400`,  
  fontSize: `70px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `108.00000429153442%`,  
  textTransform: `capitalize`,  
});
  
const PoweringFinanceForFeSpan3 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `70px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `108.00000429153442%`,  
  textTransform: `capitalize`,  
});
  
const PoweringFinanceForFe = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: "unset",  
  fontWeight: `400`,  
  fontSize: `70px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `108.00000429153442%`,  
  textTransform: `capitalize`,  
  width: `597px`,  
  margin: `0px`,  
});
  
const AccessGrowthLoansLea = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `174.00000095367432%`,  
  textTransform: `none`,  
  width: `530px`,  
  margin: `38px 0px 0px 0px`,  
});
  
const Group1000001706 = styled("div")({  
  opacity: `0`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `58.67px`,  
  width: `360px`,  
  margin: `38px 0px 0px 0px`,  
});
  
const Rectangle1031 = styled("div")({  
  backgroundColor: `rgba(3, 0, 39, 1)`,  
  borderRadius: `3px`,  
  width: `168px`,  
  height: `58.67px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group10000016601 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `123.87px`,  
  height: `28.84px`,  
  left: `22px`,  
  top: `15px`,  
});
  
const Group71331 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `84.78px`,  
  height: `28.84px`,  
  left: `39px`,  
  top: `0px`,  
});
  
const GooglePlay1 = styled("img")({  
  height: `18.05px`,  
  width: `84.78px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `11px`,  
});
  
const GetItOn1 = styled("img")({  
  height: `6.64px`,  
  width: `38.85px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const GooglePlayLogo1 = styled("div")({  
  boxShadow: `inset 0px -0.15000000596046448px 0px rgba(0, 0, 0, 0.12), inset 0px 0.15000000596046448px 0px rgba(255, 255, 255, 0.25)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `23.09px`,  
  height: `27.26px`,  
  left: `0px`,  
  top: `1px`,  
});
  
const Vector28 = styled("img")({  
  height: `26.57px`,  
  width: `12.93px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector29 = styled("img")({  
  height: `9.06px`,  
  width: `10.16px`,  
  position: `absolute`,  
  left: `13px`,  
  top: `9px`,  
});
  
const Vector30 = styled("img")({  
  height: `13.63px`,  
  width: `16.69px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `14px`,  
});
  
const Vector31 = styled("img")({  
  height: `13.63px`,  
  width: `16.69px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Rectangle1041 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 240, 248, 1)`,  
  borderRadius: `3px`,  
  width: `168px`,  
  height: `58.67px`,  
  position: `absolute`,  
  left: `192px`,  
  top: `0px`,  
}));
  
const Group71351 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `108.79px`,  
  height: `26.58px`,  
  left: `222px`,  
  top: `16px`,  
});
  
const Group71341 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `75.08px`,  
  height: `26.58px`,  
  left: `34px`,  
  top: `0px`,  
});
  
const AppStore1 = styled("img")({  
  height: `16.66px`,  
  width: `75.08px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `10px`,  
});
  
const DownloadOnThe1 = styled("img")({  
  height: `6.75px`,  
  width: `69.15px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `0px`,  
});
  
const AppleLogo1 = styled("img")({  
  height: `23px`,  
  width: `21px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `2px`,  
});
  
const Group10000017961 = styled(Group1000001796)(({ theme }) =>({  
  width: `190px`,  
  height: `55px`,  
  position: `absolute`,  
  left: `1108px`,  
  top: `60px`,  
}));
  
const MaskGroup = styled("img")({  
  height: `667.04px`,  
  width: `488.94px`,  
  position: `absolute`,  
  left: `844px`,  
  top: `186px`,  
});
  
const Frame1000002129 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  left: `101px`,  
  top: `2182px`,  
});
  
const PictureYourBusinessH = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `70px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `108.00000429153442%`,  
  textTransform: `capitalize`,  
  width: `970px`,  
  margin: `0px`,  
});
  
const Frame1000002125 = styled("div")({  
  backgroundColor: `rgba(250, 250, 250, 1)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `705px`,  
  width: `1243px`,  
  margin: `64px 0px 0px 0px`,  
  overflow: `hidden`,  
});
  
const Image52 = styled("img")({  
  height: `873px`,  
  width: `1308px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `-23px`,  
  top: `-84px`,  
});
  
const Frame1000002127 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  borderRadius: `12px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `271px`,  
  height: `80px`,  
  left: `92px`,  
  top: `128px`,  
  overflow: `hidden`,  
});
  
const GrowthLoansForYourBu = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(51, 51, 51, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `22px`,  
  textTransform: `none`,  
  width: `246px`,  
  position: `absolute`,  
  left: `20px`,  
  top: `21px`,  
});
  
const Frame1000002128 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  borderRadius: `12px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `245px`,  
  height: `80px`,  
  left: `805px`,  
  top: `573px`,  
  overflow: `hidden`,  
});
  
const BusinessInsurance = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(51, 51, 51, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `22px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `31px`,  
  top: `21px`,  
});
  
const Frame1000002131 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  left: `101px`,  
  top: `1135px`,  
});
  
const ToolsThatConnectEver = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `70px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `108.00000429153442%`,  
  textTransform: `capitalize`,  
  width: `970px`,  
  margin: `0px`,  
});
  
const Frame1000002130 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `71px 0px 0px 0px`,  
});
  
const Frame1000002121 = styled("div")({  
  backgroundColor: `rgba(250, 250, 250, 1)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `609px`,  
  height: `705px`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const Frame1000002124 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  left: `46px`,  
  top: `479px`,  
});
  
const GrowthLoans = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `32px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `135.0000023841858%`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const GetGrowthLoansForYou = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(51, 51, 51, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `167.70001649856567%`,  
  textTransform: `none`,  
  height: `66px`,  
  width: `516px`,  
  margin: `6px 0px 0px 0px`,  
});
  
const Frame10000021251 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  left: `46px`,  
  top: `607px`,  
});
  
const ViewMore = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(237, 31, 142, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `167.70001649856567%`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Arrow6 = styled("img")({  
  height: `0px`,  
  width: `24px`,  
  margin: `0px 0px 0px 9px`,  
});
  
const Frame1000002126 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `614px`,  
  height: `438px`,  
  left: `0px`,  
  top: `0px`,  
  overflow: `hidden`,  
});
  
const Image51 = styled("img")({  
  height: `520px`,  
  width: `779px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Frame10000021241 = styled("div")({  
  backgroundColor: `rgba(250, 250, 250, 1)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `609px`,  
  height: `705px`,  
  margin: `0px 0px 0px 25px`,  
  overflow: `hidden`,  
});
  
const Frame10000021242 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  left: `46px`,  
  top: `479px`,  
});
  
const Insurance = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `500`,  
  fontSize: `32px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `135.0000023841858%`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const PreserveYourGrowthAn = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(51, 51, 51, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `167.70001649856567%`,  
  textTransform: `none`,  
  height: `66px`,  
  width: `516px`,  
  margin: `6px 0px 0px 0px`,  
});
  
const Frame10000021252 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  left: `46px`,  
  top: `607px`,  
});
  
const ViewMore1 = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(237, 31, 142, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `167.70001649856567%`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Arrow61 = styled("img")({  
  height: `0px`,  
  width: `24px`,  
  margin: `0px 0px 0px 9px`,  
});
  
const Frame10000021261 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(14, 0, 8, 1)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `614px`,  
  height: `438px`,  
  left: `0px`,  
  top: `0px`,  
  overflow: `hidden`,  
}));
  
const Image54 = styled("img")({  
  height: `816px`,  
  width: `1224px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `-305px`,  
  top: `-189px`,  
});
  
const Group1000001714 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1537.13px`,  
  height: `912px`,  
  left: `-34px`,  
  top: `3235px`,  
});
  
const Group1000001712 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1463px`,  
  height: `912px`,  
  left: `25px`,  
  top: `0px`,  
});
  
const Rectangle27 = styled("div")({  
  backgroundColor: `rgba(174, 249, 130, 0.1)`,  
  borderRadius: `9.431561470031738px`,  
  width: `1463px`,  
  height: `912px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Frame1000002132 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  left: `435px`,  
  top: `523px`,  
});
  
const EnablingWomenToFlour = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(47, 139, 86, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `40px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `134.499990940094%`,  
  textTransform: `capitalize`,  
  width: `668px`,  
  margin: `0px`,  
});
  
const Group1000001722 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `58px`,  
  width: `253px`,  
  margin: `39px 0px 0px 0px`,  
});
  
const Rectangle3102 = styled("img")({  
  height: `58px`,  
  width: `253px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const JoinOurCommunity = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `19.07523536682129px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `153.20000648498535%`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `19px`,  
  top: `14px`,  
});
  
const MaskGroup1 = styled("img")({  
  height: `330.33px`,  
  width: `242.13px`,  
  position: `absolute`,  
  left: `259px`,  
  top: `140px`,  
});
  
const MaskGroup2 = styled("img")({  
  height: `330.33px`,  
  width: `242.13px`,  
  position: `absolute`,  
  left: `518px`,  
  top: `140px`,  
});
  
const MaskGroup3 = styled("img")({  
  height: `330.33px`,  
  width: `242.13px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `140px`,  
});
  
const MaskGroup4 = styled("img")({  
  height: `330.33px`,  
  width: `242.13px`,  
  position: `absolute`,  
  left: `777px`,  
  top: `140px`,  
});
  
const MaskGroup5 = styled("img")({  
  height: `330.33px`,  
  width: `242.13px`,  
  position: `absolute`,  
  left: `1036px`,  
  top: `138px`,  
});
  
const MaskGroup6 = styled("img")({  
  height: `330.33px`,  
  width: `242.13px`,  
  position: `absolute`,  
  left: `1295px`,  
  top: `138px`,  
});
  
const Frame1000002134 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1440px`,  
  height: `794px`,  
  left: `0px`,  
  top: `4147px`,  
  overflow: `hidden`,  
}));
  
const Frame1000002135 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `745px`,  
  height: `850px`,  
  left: `0px`,  
  top: `0px`,  
  overflow: `hidden`,  
});
  
const Image53 = styled("img")({  
  height: `805px`,  
  width: `1208px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `-295px`,  
  top: `0px`,  
});
  
const Frame1000002136 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  left: `831px`,  
  top: `126px`,  
});
  
const BuildingForWomenSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `46px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `capitalize`,  
});
  
const BuildingForWomenSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(235, 37, 144, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Playfair Display`,  
  fontWeight: `400`,  
  fontSize: `46px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `capitalize`,  
});
  
const BuildingForWomen = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: "unset",  
  fontWeight: `400`,  
  fontSize: `46px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `capitalize`,  
  margin: `0px`,  
});
  
const AsMyBusinessGrewIKne = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(3, 0, 39, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `400`,  
  fontSize: `19.909299850463867px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `234.50000286102295%`,  
  textTransform: `none`,  
  height: `312px`,  
  width: `540px`,  
  margin: `31px 0px 0px 0px`,  
});
  
const Group1000001686 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `133.23px`,  
  height: `55.66px`,  
  left: `823px`,  
  top: `528px`,  
});
  
const Ellipse775 = styled("img")({  
  height: `55.66px`,  
  width: `55.66px`,  
  position: `absolute`,  
  left: `78px`,  
  top: `0px`,  
});
  
const Arrow1 = styled("img")({  
  height: `0px`,  
  width: `12.8px`,  
  position: `absolute`,  
  left: `99px`,  
  top: `28px`,  
});
  
const Ellipse7751 = styled("img")({  
  height: `55.66px`,  
  width: `55.66px`,  
  position: `absolute`,  
  left: `111px`,  
  top: `56px`,  
});
  
const Arrow11 = styled("img")({  
  height: `0px`,  
  width: `12.8px`,  
  position: `absolute`,  
  left: `47px`,  
  top: `28px`,  
});
  
const Excellence = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(3, 0, 39, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Lato`,  
  fontWeight: `900`,  
  fontSize: `23.867313385009766px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `183.50000381469727%`,  
  textTransform: `none`,  
  width: `136.03px`,  
  height: `47.15px`,  
  position: `absolute`,  
  left: `821px`,  
  top: `636px`,  
});
 
function Hompage(props) {
  
    return (
    <Hompage1  className={props.className}   >
      <Community >
        {`Community`}
          </Community>
      <Insights >
        {`Insights`}
          </Insights>
      <Learn >
        {`Learn`}
          </Learn>
      <Loan >
        {`Loan`}
          </Loan>
      <AboutUs >
        {`About Us`}
          </AboutUs>
      <SignIn >
        {`Sign In`}
          </SignIn>
      <Group1000001865 >
        <Group1000001864 >
          <Group1000001704 >
            <Rectangle127 >
            </Rectangle127>
          </Group1000001704>
          <StartBuildingWealthT >
            <StartBuildingWealthTSpan1  >{`Start building wealth today
`}</StartBuildingWealthTSpan1>
            <StartBuildingWealthTSpan2  >{`Download the Shecluded app `}</StartBuildingWealthTSpan2>
          </StartBuildingWealthT>
        </Group1000001864>
        <Group1000001705 >
          <Rectangle103 >
          </Rectangle103>
          <Group1000001660 >
            <Group7133 >
              <GooglePlay  src={GooglePlayImage} alt={"Google Play"}/>
              <GetItOn  src={GetItOnImage} alt={"Get it on"}/>
            </Group7133>
            <GooglePlayLogo >
              <Vector  src={VectorImage} alt={"Vector"}/>
              <Vector1  src={Vector1Image} alt={"Vector"}/>
              <Vector2  src={Vector2Image} alt={"Vector"}/>
              <Vector3  src={Vector3Image} alt={"Vector"}/>
            </GooglePlayLogo>
          </Group1000001660>
          <Rectangle104 >
          </Rectangle104>
          <Group7135 >
            <Group7134 >
              <AppStore  src={AppStoreImage} alt={"App Store"}/>
              <DownloadOnThe  src={DownloadOnTheImage} alt={"Download on the"}/>
            </Group7134>
            <AppleLogo  src={AppleLogoImage} alt={"Apple logo"}/>
          </Group7135>
        </Group1000001705>
      </Group1000001865>
      <LogoClouds1 >
        <Divider  src={DividerImage} alt={"Divider"}/>
        <OurPartners >
          {`OUR PARTNERS`}
            </OurPartners>
        <Logos >
          <Image39  src={Image39Image} alt={"image 39"}/>
          <HubspotLogo  src={HubspotLogoImage} alt={"Hubspot Logo"}/>
          <Image3  src={Image3Image} alt={"image 3"}/>
          <MicrosoftLogo  src={MicrosoftLogoImage} alt={"Microsoft Logo"}/>
          <WalmartLogo  src={WalmartLogoImage} alt={"Walmart Logo"}/>
          <Image4  src={Image4Image} alt={"image 4"}/>
        </Logos>
        <Divider1  src={Divider1Image} alt={"Divider"}/>
      </LogoClouds1>
      <MacBookPro22 >
        <Group72 >
          <Support >
            {`Support`}
              </Support>
          <HelpCenter >
            {`Help Center`}
              </HelpCenter>
          <FaQs >
            {`FAQs`}
              </FaQs>
          <Community1 >
            {`Community`}
              </Community1>
          <ContactUs >
            {`Contact Us`}
              </ContactUs>
          <Careers >
            {`Careers`}
              </Careers>
        </Group72>
        <Group73 >
          <WhoWeAre >
            {`Who We Are`}
              </WhoWeAre>
          <AboutUs1 >
            {`About Us`}
              </AboutUs1>
          <WhatWeDo >
            {`What we do`}
              </WhatWeDo>
          <WhoWeServe >
            {`Who we serve`}
              </WhoWeServe>
          <OurPeople >
            {`Our People`}
              </OurPeople>
          <OurServices >
            {`Our Services`}
              </OurServices>
        </Group73>
        <Group43 >
          <Legal >
            {`Legal`}
              </Legal>
          <CookiesPolicy >
            {`Cookies Policy`}
              </CookiesPolicy>
          <PrivacyPolicy >
            {`Privacy Policy`}
              </PrivacyPolicy>
          <TermsOfServices >
            {`Terms Of Services`}
              </TermsOfServices>
        </Group43>
        <Group38 >
          <ConnectWithUs >
            {`Connect with us`}
              </ConnectWithUs>
          <Group30 >
            <Ellipse12  src={Ellipse12Image} alt={"Ellipse 12"}/>
            <InstagramIcon >
              <Vector4  src={Vector4Image} alt={"Vector"}/>
              <Vector5  src={Vector5Image} alt={"Vector"}/>
              <Vector6  src={Vector6Image} alt={"Vector"}/>
            </InstagramIcon>
          </Group30>
          <Group29 >
            <Ellipse13  src={Ellipse13Image} alt={"Ellipse 13"}/>
            <TwitterLogo >
              <Group >
                <Vector7  src={Vector7Image} alt={"Vector"}/>
              </Group>
            </TwitterLogo>
          </Group29>
          <Group28 >
            <Ellipse14  src={Ellipse14Image} alt={"Ellipse 14"}/>
            <FacebookIcon >
              <G10 >
                <G12 >
                  {false &&
                    <Path14  src={Path14Image} alt={"path14"}/>
                  }
                  <Path16  src={Path16Image} alt={"path16"}/>
                </G12>
              </G10>
            </FacebookIcon>
          </Group28>
          <Group27 >
            <Ellipse15  src={Ellipse15Image} alt={"Ellipse 15"}/>
            <LinkedInIcon >
              <Path2520  src={Path2520Image} alt={"Path 2520"}/>
            </LinkedInIcon>
          </Group27>
        </Group38>
        <ThisSiteUsesCookiesC >
          <ThisSiteUsesCookiesCSpan1  >{`This site uses cookies. `}</ThisSiteUsesCookiesCSpan1>
          <ThisSiteUsesCookiesCSpan2  >{`Cookie and Privacy Policy. `}</ThisSiteUsesCookiesCSpan2>
          <ThisSiteUsesCookiesCSpan3  >{`I agree to the`}</ThisSiteUsesCookiesCSpan3>
          <ThisSiteUsesCookiesCSpan4  >{` terms of use`}</ThisSiteUsesCookiesCSpan4>
          <ThisSiteUsesCookiesCSpan5  >{`, and the `}</ThisSiteUsesCookiesCSpan5>
          <ThisSiteUsesCookiesCSpan6  >{`Disclaimer Policy`}</ThisSiteUsesCookiesCSpan6>
          <ThisSiteUsesCookiesCSpan7  >{`.This Information will not be used for marketing purposes.`}</ThisSiteUsesCookiesCSpan7>
        </ThisSiteUsesCookiesC>
        <Copyright2021Sheclud >
          {`Copyright 2021 Shecluded Solutions Ltd.`}
            </Copyright2021Sheclud>
        <Vector51  src={Vector51Image} alt={"Vector 5"}/>
        <Col4 >
          <InstallApp >
            {`Install App`}
              </InstallApp>
          <Badges >
            <DownloadBadgeGoogleP   />
            <DownloadBadgeAppStor   />
          </Badges>
        </Col4>
        <Logo21 >
          <Layer2 >
            <Layer1 >
              <Vector8  src={Vector8Image} alt={"Vector"}/>
              <Vector9  src={Vector9Image} alt={"Vector"}/>
              <Vector10  src={Vector10Image} alt={"Vector"}/>
              <Vector11  src={Vector11Image} alt={"Vector"}/>
              <Vector12  src={Vector12Image} alt={"Vector"}/>
              <Vector13  src={Vector13Image} alt={"Vector"}/>
              <Vector14  src={Vector14Image} alt={"Vector"}/>
              <Vector15  src={Vector15Image} alt={"Vector"}/>
              <Vector16  src={Vector16Image} alt={"Vector"}/>
              <Vector17  src={Vector17Image} alt={"Vector"}/>
            </Layer1>
          </Layer2>
        </Logo21>
        <Newsletter >
          <SubscribeToOurNew >
            {`Subscribe to our
newsletter`}
              </SubscribeToOurNew>
          <Form >
            <Rectangle >
            </Rectangle>
            <EmailAddress >
              {`Email address`}
                </EmailAddress>
            <Submit >
              <Rectangle1 >
              </Rectangle1>
              <IcKeyboardArrowRight >
                <Path  src={PathImage} alt={"Path"}/>
                <Path1  src={Path1Image} alt={"Path"}/>
              </IcKeyboardArrowRight>
            </Submit>
          </Form>
        </Newsletter>
      </MacBookPro22>
      <Layer21 >
        <Layer11 >
          <Vector18  src={Vector18Image} alt={"Vector"}/>
          <Vector19  src={Vector19Image} alt={"Vector"}/>
          <Vector20  src={Vector20Image} alt={"Vector"}/>
          <Vector21  src={Vector21Image} alt={"Vector"}/>
          <Vector22  src={Vector22Image} alt={"Vector"}/>
          <Vector23  src={Vector23Image} alt={"Vector"}/>
          <Vector24  src={Vector24Image} alt={"Vector"}/>
          <Vector25  src={Vector25Image} alt={"Vector"}/>
          <Vector26  src={Vector26Image} alt={"Vector"}/>
          <Vector27  src={Vector27Image} alt={"Vector"}/>
        </Layer11>
      </Layer21>
      <Frame1000002123 >
        <Group1000001813 >
          <Rectangle3110 >
          </Rectangle3110>
          <BrandAnnouncementWeH >
            <BrandAnnouncementWeHSpan1  >{`Brand Announcement: We have new loans for you, `}</BrandAnnouncementWeHSpan1>
            <BrandAnnouncementWeHSpan2  >{`check them out`}</BrandAnnouncementWeHSpan2>
          </BrandAnnouncementWeH>
        </Group1000001813>
        <Frame1000002122 >
          <PoweringFinanceForFe >
            <PoweringFinanceForFeSpan1  >{`Powering `}</PoweringFinanceForFeSpan1>
            <PoweringFinanceForFeSpan2  >{`finance`}</PoweringFinanceForFeSpan2>
            <PoweringFinanceForFeSpan3  >{` for Female Entrepreneurs `}</PoweringFinanceForFeSpan3>
          </PoweringFinanceForFe>
          <AccessGrowthLoansLea >
            {`Access Growth loans, learn about money and build your wealth with the shecluded membership.`}
              </AccessGrowthLoansLea>
          <Group1000001706 >
            <Rectangle1031 >
            </Rectangle1031>
            <Group10000016601 >
              <Group71331 >
                <GooglePlay1  src={GooglePlay1Image} alt={"Google Play"}/>
                <GetItOn1  src={GetItOn1Image} alt={"Get it on"}/>
              </Group71331>
              <GooglePlayLogo1 >
                <Vector28  src={Vector28Image} alt={"Vector"}/>
                <Vector29  src={Vector29Image} alt={"Vector"}/>
                <Vector30  src={Vector30Image} alt={"Vector"}/>
                <Vector31  src={Vector31Image} alt={"Vector"}/>
              </GooglePlayLogo1>
            </Group10000016601>
            <Rectangle1041 >
            </Rectangle1041>
            <Group71351 >
              <Group71341 >
                <AppStore1  src={AppStore1Image} alt={"App Store"}/>
                <DownloadOnThe1  src={DownloadOnThe1Image} alt={"Download on the"}/>
              </Group71341>
              <AppleLogo1  src={AppleLogo1Image} alt={"Apple logo"}/>
            </Group71351>
          </Group1000001706>
        </Frame1000002122>
      </Frame1000002123>
      <Group10000017961   />
      <MaskGroup  src={MaskGroupImage} alt={"Mask Group"}/>
      <Frame1000002129 >
        <PictureYourBusinessH >
          {`Picture your business here`}
            </PictureYourBusinessH>
        <Frame1000002125 >
          <Image52  src={Image52Image} alt={"image 52"}/>
          <Frame1000002127 >
            <GrowthLoansForYourBu >
              {`Growth loans for your business`}
                </GrowthLoansForYourBu>
          </Frame1000002127>
          <Frame1000002128 >
            <BusinessInsurance >
              {`Business Insurance`}
                </BusinessInsurance>
          </Frame1000002128>
        </Frame1000002125>
      </Frame1000002129>
      <Frame1000002131 >
        <ToolsThatConnectEver >
          {`Tools that connect everyside of your business.`}
            </ToolsThatConnectEver>
        <Frame1000002130 >
          <Frame1000002121 >
            <Frame1000002124 >
              <GrowthLoans >
                {`Growth Loans`}
                  </GrowthLoans>
              <GetGrowthLoansForYou >
                {`Get Growth loans for your business and live out your dreams`}
                  </GetGrowthLoansForYou>
            </Frame1000002124>
            <Frame10000021251 >
              <ViewMore >
                {`View More`}
                  </ViewMore>
              <Arrow6  src={Arrow6Image} alt={"Arrow 6"}/>
            </Frame10000021251>
            <Frame1000002126 >
              <Image51  src={Image51Image} alt={"image 51"}/>
            </Frame1000002126>
          </Frame1000002121>
          <Frame10000021241 >
            <Frame10000021242 >
              <Insurance >
                {`Insurance`}
                  </Insurance>
              <PreserveYourGrowthAn >
                {`Preserve your growth and get covered by our insurance plans ranging from health, cars, business, life insurance`}
                  </PreserveYourGrowthAn>
            </Frame10000021242>
            <Frame10000021252 >
              <ViewMore1 >
                {`View More`}
                  </ViewMore1>
              <Arrow61  src={Arrow61Image} alt={"Arrow 6"}/>
            </Frame10000021252>
            <Frame10000021261 >
              <Image54  src={Image54Image} alt={"image 54"}/>
            </Frame10000021261>
          </Frame10000021241>
        </Frame1000002130>
      </Frame1000002131>
      <Group1000001714 >
        <Group1000001712 >
          <Rectangle27 >
          </Rectangle27>
        </Group1000001712>
        <Frame1000002132 >
          <EnablingWomenToFlour >
            {`enabling women to flourish and grow on their journey from ambition to achievement `}
              </EnablingWomenToFlour>
          <Group1000001722 >
            <Rectangle3102  src={Rectangle3102Image} alt={"Rectangle 3102"}/>
            <JoinOurCommunity >
              {`JOIN OUR COMMUNITY`}
                </JoinOurCommunity>
          </Group1000001722>
        </Frame1000002132>
        <MaskGroup1  src={MaskGroup1Image} alt={"Mask Group"}/>
        <MaskGroup2  src={MaskGroup2Image} alt={"Mask Group"}/>
        <MaskGroup3  src={MaskGroup3Image} alt={"Mask Group"}/>
        <MaskGroup4  src={MaskGroup4Image} alt={"Mask Group"}/>
        <MaskGroup5  src={MaskGroup5Image} alt={"Mask Group"}/>
        <MaskGroup6  src={MaskGroup6Image} alt={"Mask Group"}/>
      </Group1000001714>
      <Frame1000002134 >
        <Frame1000002135 >
          <Image53  src={Image53Image} alt={"image 53"}/>
        </Frame1000002135>
        <Frame1000002136 >
          <BuildingForWomen >
            <BuildingForWomenSpan1  >{`Building `}</BuildingForWomenSpan1>
            <BuildingForWomenSpan2  >{`For Women`}</BuildingForWomenSpan2>
          </BuildingForWomen>
          <AsMyBusinessGrewIKne >
            {`“As my business grew, I knew I needed to invest in a better laptop. I didn’t have the chunk of money to purchase what I needed; a MacBook, so I reached out to shecluded, and they offered me a good loan and a good repayment plan to get what I needed to optimize my process. The loan process and disbursement were fast and seamless.”`}
              </AsMyBusinessGrewIKne>
        </Frame1000002136>
        <Group1000001686 >
          <Ellipse775  src={Ellipse775Image} alt={"Ellipse 775"}/>
          <Arrow1  src={Arrow1Image} alt={"Arrow 1"}/>
          <Ellipse7751  src={Ellipse7751Image} alt={"Ellipse 775"}/>
          <Arrow11  src={Arrow11Image} alt={"Arrow 1"}/>
        </Group1000001686>
        <Excellence >
          {`– Excellence
`}
            </Excellence>
      </Frame1000002134>
    </Hompage1>
  );
}

export default Hompage;
